GET http://localhost:4321/api/genres
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2I3MTEzNmZlZDQxM2Q2YmIwNDk1NTkiLCJuYW1lIjoiTmlqaSBBYmR1bGF6ZWVtIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzQwMTM4MDYyfQ.Sbl4Vq_KPJTUBkXUfGqRchLMaCnkQcRJvykeKZVPtz0
